name: Idletests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
        
      - name: Setup pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest pyyaml rich
        
      - name: Run the tests
        run: python -m pytest
